image: openjdk:17-jdk

stages:
  - test
  - deploy

before_script:
  - PATH=/opt/apache-maven-3.8.6/bin:/usr/local/openjdk-17/bin:$PATH
  - JAVA_HOME=\Program Files\Java\jdk-17

test-all:
  stage: test
  tags: [maven]
  except:
    - master
    - main
  script:
    - mvn clean install

test-unit:
  stage: test
  tags: [maven]
  only:
    - master
    - main
  script:
    - mvn clean package
  artifacts:
    name: backend-social-network
    expire_in: 1 week


deploy:
  stage: deploy
  needs: [test-unit]
  only:
    - master
    - main