version: '3.8'

services:
  postgres-db:
    image: postgres:13
    container_name: postgres-adaptive
    environment:
      POSTGRES_DB: adaptive-DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - adaptive-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-adaptive
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@open.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
    networks:
      - adaptive-net

volumes:
  postgres_data:

networks:
  adaptive-net:
    driver: bridge
    attachable: true  # Option recommandée