version: '3.8'

services:
  mongodb:
    image: mongo:6.0.10
    container_name: mongo-ad
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: adaptive
      MONGO_INITDB_ROOT_PASSWORD: adaptive
      MONGO_INITDB_DATABASE: admin
    networks:
      - adaptive-net  # Utilisation de votre réseau existant
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:1.0.0
    container_name: mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: adaptive
      ME_CONFIG_MONGODB_ADMINPASSWORD: adaptive
      ME_CONFIG_MONGODB_SERVER: mongodb  # Utilise le nom du service
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - adaptive-net  # Même réseau que MongoDB

volumes:
  mongodb_data:

networks:
  adaptive-net:  # Déclaration du réseau existant
    external: true
    name: adaptive-net  # Nom exact de votre réseau