version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    networks:
      - adaptive-net
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    volumes:
      - mailhog_data:/maildir
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /maildir
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8025"]
      interval: 10s

volumes:
  mailhog_data:

networks:
  adaptive-net:
    external: true